language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
    - export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    # fix for new build issue on travis: /home/travis/.travis/job_stages: line 57: ./node_modules/.bin/yarn: No such file or directory
    #- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn global add greenkeeper-lockfile@1
    - which yarn
    - echo $PATH
install:
    - |
      if [[ $BRANCH == "greenkeeper/"* ]]; then
        echo Greenkeeper build using .yarnrc.greenkeeper; cp .yarnrc.greenkeeper .yarnrc; yarn install;
      else
        echo Normal build using .yarnrc and --frozen-lockfile option; yarn install --frozen-lockfile;
      fi
before_script:
    - echo $PATH
    - which yarn
    - greenkeeper-lockfile-update
    - yarn --version && yarn bin && yarn webpack --version && yarn webpack --version
    - yarn build:development # temporaly not yarn build:production until errors with minified bundle are not resolved
    - yarn serve:production &
script:
    - yarn test
# discord webhooks hack until this is released: https://github.com/travis-ci/travis-tasks/pull/71
after_script:
    - greenkeeper-lockfile-upload
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/418374581749809171/cJ8pkKO40Uoud2BU-rI_EqAvssHT2r60_6CTl00ds96_jfv1B_c_iukZjhWbg9qzcbhe
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/418374581749809171/cJ8pkKO40Uoud2BU-rI_EqAvssHT2r60_6CTl00ds96_jfv1B_c_iukZjhWbg9qzcbhe
